DROP TABLE IF EXISTS member_image;
DROP TABLE IF EXISTS member_detail;
DROP TABLE IF EXISTS member_address;
DROP TABLE IF EXISTS member;

DROP TABLE IF EXISTS banner_file;
DROP TABLE IF EXISTS banner;


