server:
  port: 10800

spring:
  main:
    allow-circular-references: true
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://${rds-url}:${rds-port}/${rds-schema}
    username: ${rds-user}
    password: ${rds-pass}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

  sql:
    init:
      schema-locations:
        classpath*:db/prod/schema.sql,
#        classpath*:db/alter_table.sql,
        classpath*:db/prod/data.sql
      mode: always

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  mail:
    host: ${mail-host}
    port: 587
    username: ${mail-user}
    password: ${mail-pass}


logging:
  level:
    root: debug
    org.hibernate.sql: debug
    org.springframework.boot: info
    com.galaxypoby.dogwhiz: debug

path:
  rootURL: ${web-server}

jwt:
  issuer: hellodogwhiz.com
  secret_key: ${secretKey}
