spring:
  datasource:
    url: jdbc:mariadb://58.238.182.90:10401/dogwhiz
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  sql:
    init:
      schema-locations:
        classpath*:db/drop_table.sql,
        classpath*:db/schema.sql
#        classpath*:db/alter_table.sql,
#        classpath*:db/data.sql,
      mode: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
server:
  port: 8080

