# Spring Boot configuration for the "dev" profile.

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  sql:
    init:
      schema-locations:
        classpath*:db/drop_table.sql,
        classpath*:db/dev/schema.sql,
        classpath*:db/dev/data.sql
#       classpath*:db/alter_table.sql
      mode: always

logging:
  level:
    root: debug
    org.hibernate.sql: debug
    org.springframework.boot: info
    com.galaxypoby.dogwhiz: debug

jwt:
  issuer: dev.hellodogwhiz.com
