spring:
  datasource:
    url: jdbc:mariadb://58.238.182.90:10401/dogwhiz
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false



logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

path:
  rootURL: https://dev.webserver.hellodogwhiz.com/

server:
  port: 10800



